"""add index on jobs.status

Revision ID: 664a8f513aa2
Revises: 36d26376ef62
Create Date: 2026-08-26 11:32:05.278879

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "664a8f513aa2"
down_revision: str | Sequence[str] | None = "36d26376ef62"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    # ### end Alembic commands ###
