"""add processed_email_messages table

Revision ID: 9fd80046ea7e
Revises: 664a8f513aa2
Create Date: 2026-08-26 13:36:38.764091

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9fd80046ea7e"
down_revision: str | Sequence[str] | None = "664a8f513aa2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processed_email_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("message_id", sa.String(length=998), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_processed_email_messages_message_id"),
        "processed_email_messages",
        ["message_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_processed_email_messages_source"),
        "processed_email_messages",
        ["source"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_processed_email_messages_source"), table_name="processed_email_messages")
    op.drop_index(
        op.f("ix_processed_email_messages_message_id"), table_name="processed_email_messages"
    )
    op.drop_table("processed_email_messages")
    # ### end Alembic commands ###
